title: "Crime Evolution in Latin America 2015-2024: Database by Cate"
description: "Database on the evolution of crime in Latin America and the Caribbean during the period 2015-2024, compiled from secondary sources (UNODC, InSight Cri"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/crime-evolution-in-latin-america-2015-2024-database-by-categories"
